[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/chat"
  to = "/chat.html"
  status = 200

[[redirects]]
  from = "/bot-posts"
  to = "/bot-posts.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
